sudo: false
language: node_js
node_js:
- 4.1

addons:
  sauce_connect: true

env:
  matrix:
    - BROWSER=chrome
    - BROWSER=chrome BVER=beta
    - BROWSER=chrome BVER=dev
    - BROWSER=firefox
    - BROWSER=firefox BVER=beta
    - BROWSER=firefox BVER=dev

matrix:
  fast_finish: true
  allow_failures:
    - env: BROWSER=firefox

script:
  - npm test

after_failure:
  - for file in *.log; do echo $file; echo "======================"; cat $file; done || true

